DROP TABLE IF EXISTS blogful_articles; 
CREATE TABLE blogful_articles (
    id Integer Primary Key Generated BY DEFAULT As Identity,
    title Text NOT NULL,
    content TEXT,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
    

);